# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1130, 817)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1109, 802))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left.sizePolicy().hasHeightForWidth())
        self.frame_left.setSizePolicy(sizePolicy)
        self.frame_left.setMinimumSize(QtCore.QSize(200, 800))
        self.frame_left.setMaximumSize(QtCore.QSize(200, 800))
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_flight = QtWidgets.QPushButton(self.frame_left)
        self.button_flight.setMinimumSize(QtCore.QSize(0, 60))
        self.button_flight.setObjectName("button_flight")
        self.verticalLayout.addWidget(self.button_flight)
        self.button_passenger = QtWidgets.QPushButton(self.frame_left)
        self.button_passenger.setMinimumSize(QtCore.QSize(0, 60))
        self.button_passenger.setObjectName("button_passenger")
        self.verticalLayout.addWidget(self.button_passenger)
        self.button_seat = QtWidgets.QPushButton(self.frame_left)
        self.button_seat.setMinimumSize(QtCore.QSize(0, 60))
        self.button_seat.setObjectName("button_seat")
        self.verticalLayout.addWidget(self.button_seat)
        self.button_bill = QtWidgets.QPushButton(self.frame_left)
        self.button_bill.setMinimumSize(QtCore.QSize(0, 60))
        self.button_bill.setObjectName("button_bill")
        self.verticalLayout.addWidget(self.button_bill)
        self.horizontalLayout.addWidget(self.frame_left)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.table_flight = QtWidgets.QTableWidget(self.page)
        self.table_flight.setGeometry(QtCore.QRect(20, 70, 851, 701))
        self.table_flight.setRowCount(100)
        self.table_flight.setColumnCount(7)
        self.table_flight.setObjectName("table_flight")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(30, 10, 831, 52))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_flight_add = QtWidgets.QPushButton(self.frame)
        self.pushButton_flight_add.setObjectName("pushButton_flight_add")
        self.horizontalLayout_2.addWidget(self.pushButton_flight_add)
        self.pushButton_flight_del = QtWidgets.QPushButton(self.frame)
        self.pushButton_flight_del.setObjectName("pushButton_flight_del")
        self.horizontalLayout_2.addWidget(self.pushButton_flight_del)
        self.pushButton_flight_mod = QtWidgets.QPushButton(self.frame)
        self.pushButton_flight_mod.setObjectName("pushButton_flight_mod")
        self.horizontalLayout_2.addWidget(self.pushButton_flight_mod)
        self.pushButton_flight_ser = QtWidgets.QPushButton(self.frame)
        self.pushButton_flight_ser.setObjectName("pushButton_flight_ser")
        self.horizontalLayout_2.addWidget(self.pushButton_flight_ser)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.table_passenger = QtWidgets.QTableWidget(self.page_2)
        self.table_passenger.setGeometry(QtCore.QRect(20, 70, 851, 701))
        self.table_passenger.setRowCount(100)
        self.table_passenger.setColumnCount(5)
        self.table_passenger.setObjectName("table_passenger")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(30, 10, 831, 52))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_passenger_add = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_passenger_add.setObjectName("pushButton_passenger_add")
        self.horizontalLayout_3.addWidget(self.pushButton_passenger_add)
        self.pushButton_passenger_del = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_passenger_del.setObjectName("pushButton_passenger_del")
        self.horizontalLayout_3.addWidget(self.pushButton_passenger_del)
        self.pushButton_passenger_mod = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_passenger_mod.setObjectName("pushButton_passenger_mod")
        self.horizontalLayout_3.addWidget(self.pushButton_passenger_mod)
        self.pushButton_passenger_ser = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_passenger_ser.setObjectName("pushButton_passenger_ser")
        self.horizontalLayout_3.addWidget(self.pushButton_passenger_ser)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.list_flight = QtWidgets.QListWidget(self.page_3)
        self.list_flight.setGeometry(QtCore.QRect(20, 30, 101, 741))
        self.list_flight.setObjectName("list_flight")
        self.frame_seat = QtWidgets.QFrame(self.page_3)
        self.frame_seat.setGeometry(QtCore.QRect(140, 30, 731, 741))
        self.frame_seat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_seat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_seat.setObjectName("frame_seat")
        self.frame_seat_l = QtWidgets.QFrame(self.frame_seat)
        self.frame_seat_l.setGeometry(QtCore.QRect(70, 150, 131, 455))
        self.frame_seat_l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_seat_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_seat_l.setObjectName("frame_seat_l")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_seat_l)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_b3 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b3.setObjectName("pushButton_b3")
        self.gridLayout.addWidget(self.pushButton_b3, 4, 1, 1, 1)
        self.pushButton_a3 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a3.setObjectName("pushButton_a3")
        self.gridLayout.addWidget(self.pushButton_a3, 4, 0, 1, 1)
        self.pushButton_a6 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a6.setObjectName("pushButton_a6")
        self.gridLayout.addWidget(self.pushButton_a6, 9, 0, 1, 1)
        self.pushButton_b6 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b6.setObjectName("pushButton_b6")
        self.gridLayout.addWidget(self.pushButton_b6, 9, 1, 1, 1)
        self.pushButton_b1 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b1.setObjectName("pushButton_b1")
        self.gridLayout.addWidget(self.pushButton_b1, 0, 1, 1, 1)
        self.pushButton_c5 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c5.setObjectName("pushButton_c5")
        self.gridLayout.addWidget(self.pushButton_c5, 8, 2, 1, 1)
        self.pushButton_b7 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b7.setObjectName("pushButton_b7")
        self.gridLayout.addWidget(self.pushButton_b7, 10, 1, 1, 1)
        self.pushButton_a1 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a1.setObjectName("pushButton_a1")
        self.gridLayout.addWidget(self.pushButton_a1, 0, 0, 1, 1)
        self.pushButton_c6 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c6.setObjectName("pushButton_c6")
        self.gridLayout.addWidget(self.pushButton_c6, 9, 2, 1, 1)
        self.pushButton_b4 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b4.setObjectName("pushButton_b4")
        self.gridLayout.addWidget(self.pushButton_b4, 6, 1, 1, 1)
        self.pushButton_a7 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a7.setObjectName("pushButton_a7")
        self.gridLayout.addWidget(self.pushButton_a7, 10, 0, 1, 1)
        self.pushButton_a2 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a2.setObjectName("pushButton_a2")
        self.gridLayout.addWidget(self.pushButton_a2, 2, 0, 1, 1)
        self.pushButton_a4 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a4.setObjectName("pushButton_a4")
        self.gridLayout.addWidget(self.pushButton_a4, 6, 0, 1, 1)
        self.pushButton_b5 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b5.setObjectName("pushButton_b5")
        self.gridLayout.addWidget(self.pushButton_b5, 8, 1, 1, 1)
        self.pushButton_a5 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a5.setObjectName("pushButton_a5")
        self.gridLayout.addWidget(self.pushButton_a5, 8, 0, 1, 1)
        self.pushButton_b2 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b2.setObjectName("pushButton_b2")
        self.gridLayout.addWidget(self.pushButton_b2, 2, 1, 1, 1)
        self.pushButton_a10 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a10.setObjectName("pushButton_a10")
        self.gridLayout.addWidget(self.pushButton_a10, 16, 0, 1, 1)
        self.pushButton_a9 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a9.setObjectName("pushButton_a9")
        self.gridLayout.addWidget(self.pushButton_a9, 15, 0, 1, 1)
        self.pushButton_b11 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b11.setObjectName("pushButton_b11")
        self.gridLayout.addWidget(self.pushButton_b11, 17, 1, 1, 1)
        self.pushButton_a11 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a11.setObjectName("pushButton_a11")
        self.gridLayout.addWidget(self.pushButton_a11, 17, 0, 1, 1)
        self.pushButton_b10 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b10.setObjectName("pushButton_b10")
        self.gridLayout.addWidget(self.pushButton_b10, 16, 1, 1, 1)
        self.pushButton_b8 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b8.setObjectName("pushButton_b8")
        self.gridLayout.addWidget(self.pushButton_b8, 13, 1, 1, 1)
        self.pushButton_b9 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_b9.setObjectName("pushButton_b9")
        self.gridLayout.addWidget(self.pushButton_b9, 15, 1, 1, 1)
        self.pushButton_c2 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c2.setObjectName("pushButton_c2")
        self.gridLayout.addWidget(self.pushButton_c2, 2, 2, 1, 1)
        self.pushButton_a8 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_a8.setObjectName("pushButton_a8")
        self.gridLayout.addWidget(self.pushButton_a8, 13, 0, 1, 1)
        self.pushButton_c7 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c7.setObjectName("pushButton_c7")
        self.gridLayout.addWidget(self.pushButton_c7, 10, 2, 1, 1)
        self.pushButton_c8 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c8.setObjectName("pushButton_c8")
        self.gridLayout.addWidget(self.pushButton_c8, 13, 2, 1, 1)
        self.pushButton_c9 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c9.setObjectName("pushButton_c9")
        self.gridLayout.addWidget(self.pushButton_c9, 15, 2, 1, 1)
        self.pushButton_c4 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c4.setObjectName("pushButton_c4")
        self.gridLayout.addWidget(self.pushButton_c4, 6, 2, 1, 1)
        self.pushButton_c10 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c10.setObjectName("pushButton_c10")
        self.gridLayout.addWidget(self.pushButton_c10, 16, 2, 1, 1)
        self.pushButton_c3 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c3.setObjectName("pushButton_c3")
        self.gridLayout.addWidget(self.pushButton_c3, 4, 2, 1, 1)
        self.pushButton_c11 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c11.setObjectName("pushButton_c11")
        self.gridLayout.addWidget(self.pushButton_c11, 17, 2, 1, 1)
        self.pushButton_c1 = QtWidgets.QPushButton(self.frame_seat_l)
        self.pushButton_c1.setObjectName("pushButton_c1")
        self.gridLayout.addWidget(self.pushButton_c1, 0, 2, 1, 1)
        self.frame_seat_c = QtWidgets.QFrame(self.frame_seat)
        self.frame_seat_c.setGeometry(QtCore.QRect(280, 150, 171, 451))
        self.frame_seat_c.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_seat_c.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_seat_c.setObjectName("frame_seat_c")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_seat_c)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_f9 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f9.setObjectName("pushButton_f9")
        self.gridLayout_2.addWidget(self.pushButton_f9, 8, 1, 1, 1)
        self.pushButton_g9 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g9.setObjectName("pushButton_g9")
        self.gridLayout_2.addWidget(self.pushButton_g9, 8, 2, 1, 1)
        self.pushButton_f10 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f10.setObjectName("pushButton_f10")
        self.gridLayout_2.addWidget(self.pushButton_f10, 9, 1, 1, 1)
        self.pushButton_h9 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h9.setObjectName("pushButton_h9")
        self.gridLayout_2.addWidget(self.pushButton_h9, 8, 3, 1, 1)
        self.pushButton_h10 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h10.setObjectName("pushButton_h10")
        self.gridLayout_2.addWidget(self.pushButton_h10, 9, 3, 1, 1)
        self.pushButton_e10 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e10.setObjectName("pushButton_e10")
        self.gridLayout_2.addWidget(self.pushButton_e10, 9, 0, 1, 1)
        self.pushButton_g10 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g10.setObjectName("pushButton_g10")
        self.gridLayout_2.addWidget(self.pushButton_g10, 9, 2, 1, 1)
        self.pushButton_e7 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e7.setObjectName("pushButton_e7")
        self.gridLayout_2.addWidget(self.pushButton_e7, 6, 0, 1, 1)
        self.pushButton_f2 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f2.setObjectName("pushButton_f2")
        self.gridLayout_2.addWidget(self.pushButton_f2, 1, 1, 1, 1)
        self.pushButton_h2 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h2.setObjectName("pushButton_h2")
        self.gridLayout_2.addWidget(self.pushButton_h2, 1, 3, 1, 1)
        self.pushButton_e9 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e9.setObjectName("pushButton_e9")
        self.gridLayout_2.addWidget(self.pushButton_e9, 8, 0, 1, 1)
        self.pushButton_g3 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g3.setObjectName("pushButton_g3")
        self.gridLayout_2.addWidget(self.pushButton_g3, 2, 2, 1, 1)
        self.pushButton_g8 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g8.setObjectName("pushButton_g8")
        self.gridLayout_2.addWidget(self.pushButton_g8, 7, 2, 1, 1)
        self.pushButton_f3 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f3.setObjectName("pushButton_f3")
        self.gridLayout_2.addWidget(self.pushButton_f3, 2, 1, 1, 1)
        self.pushButton_e4 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e4.setObjectName("pushButton_e4")
        self.gridLayout_2.addWidget(self.pushButton_e4, 3, 0, 1, 1)
        self.pushButton_g1 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g1.setObjectName("pushButton_g1")
        self.gridLayout_2.addWidget(self.pushButton_g1, 0, 2, 1, 1)
        self.pushButton_h1 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h1.setObjectName("pushButton_h1")
        self.gridLayout_2.addWidget(self.pushButton_h1, 0, 3, 1, 1)
        self.pushButton_f8 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f8.setObjectName("pushButton_f8")
        self.gridLayout_2.addWidget(self.pushButton_f8, 7, 1, 1, 1)
        self.pushButton_e6 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e6.setObjectName("pushButton_e6")
        self.gridLayout_2.addWidget(self.pushButton_e6, 5, 0, 1, 1)
        self.pushButton_h3 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h3.setObjectName("pushButton_h3")
        self.gridLayout_2.addWidget(self.pushButton_h3, 2, 3, 1, 1)
        self.pushButton_h4 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h4.setObjectName("pushButton_h4")
        self.gridLayout_2.addWidget(self.pushButton_h4, 3, 3, 1, 1)
        self.pushButton_f4 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f4.setObjectName("pushButton_f4")
        self.gridLayout_2.addWidget(self.pushButton_f4, 3, 1, 1, 1)
        self.pushButton_h5 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h5.setObjectName("pushButton_h5")
        self.gridLayout_2.addWidget(self.pushButton_h5, 4, 3, 1, 1)
        self.pushButton_g4 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g4.setObjectName("pushButton_g4")
        self.gridLayout_2.addWidget(self.pushButton_g4, 3, 2, 1, 1)
        self.pushButton_e5 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e5.setObjectName("pushButton_e5")
        self.gridLayout_2.addWidget(self.pushButton_e5, 4, 0, 1, 1)
        self.pushButton_g5 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g5.setObjectName("pushButton_g5")
        self.gridLayout_2.addWidget(self.pushButton_g5, 4, 2, 1, 1)
        self.pushButton_f5 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f5.setObjectName("pushButton_f5")
        self.gridLayout_2.addWidget(self.pushButton_f5, 4, 1, 1, 1)
        self.pushButton_f7 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f7.setObjectName("pushButton_f7")
        self.gridLayout_2.addWidget(self.pushButton_f7, 6, 1, 1, 1)
        self.pushButton_g6 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g6.setObjectName("pushButton_g6")
        self.gridLayout_2.addWidget(self.pushButton_g6, 5, 2, 1, 1)
        self.pushButton_f6 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f6.setObjectName("pushButton_f6")
        self.gridLayout_2.addWidget(self.pushButton_f6, 5, 1, 1, 1)
        self.pushButton_h6 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h6.setObjectName("pushButton_h6")
        self.gridLayout_2.addWidget(self.pushButton_h6, 5, 3, 1, 1)
        self.pushButton_g2 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g2.setObjectName("pushButton_g2")
        self.gridLayout_2.addWidget(self.pushButton_g2, 1, 2, 1, 1)
        self.pushButton_g7 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g7.setObjectName("pushButton_g7")
        self.gridLayout_2.addWidget(self.pushButton_g7, 6, 2, 1, 1)
        self.pushButton_e2 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e2.setObjectName("pushButton_e2")
        self.gridLayout_2.addWidget(self.pushButton_e2, 1, 0, 1, 1)
        self.pushButton_f1 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f1.setObjectName("pushButton_f1")
        self.gridLayout_2.addWidget(self.pushButton_f1, 0, 1, 1, 1)
        self.pushButton_e1 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e1.setObjectName("pushButton_e1")
        self.gridLayout_2.addWidget(self.pushButton_e1, 0, 0, 1, 1)
        self.pushButton_h7 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h7.setObjectName("pushButton_h7")
        self.gridLayout_2.addWidget(self.pushButton_h7, 6, 3, 1, 1)
        self.pushButton_e3 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e3.setObjectName("pushButton_e3")
        self.gridLayout_2.addWidget(self.pushButton_e3, 2, 0, 1, 1)
        self.pushButton_h8 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h8.setObjectName("pushButton_h8")
        self.gridLayout_2.addWidget(self.pushButton_h8, 7, 3, 1, 1)
        self.pushButton_e8 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e8.setObjectName("pushButton_e8")
        self.gridLayout_2.addWidget(self.pushButton_e8, 7, 0, 1, 1)
        self.pushButton_e11 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_e11.setObjectName("pushButton_e11")
        self.gridLayout_2.addWidget(self.pushButton_e11, 10, 0, 1, 1)
        self.pushButton_f11 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_f11.setObjectName("pushButton_f11")
        self.gridLayout_2.addWidget(self.pushButton_f11, 10, 1, 1, 1)
        self.pushButton_g11 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_g11.setObjectName("pushButton_g11")
        self.gridLayout_2.addWidget(self.pushButton_g11, 10, 2, 1, 1)
        self.pushButton_h11 = QtWidgets.QPushButton(self.frame_seat_c)
        self.pushButton_h11.setObjectName("pushButton_h11")
        self.gridLayout_2.addWidget(self.pushButton_h11, 10, 3, 1, 1)
        self.frame_seat_r = QtWidgets.QFrame(self.frame_seat)
        self.frame_seat_r.setGeometry(QtCore.QRect(530, 150, 131, 451))
        self.frame_seat_r.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_seat_r.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_seat_r.setObjectName("frame_seat_r")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_seat_r)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_j1 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j1.setObjectName("pushButton_j1")
        self.gridLayout_3.addWidget(self.pushButton_j1, 0, 0, 1, 1)
        self.pushButton_j2 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j2.setObjectName("pushButton_j2")
        self.gridLayout_3.addWidget(self.pushButton_j2, 1, 0, 1, 1)
        self.pushButton_j9 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j9.setObjectName("pushButton_j9")
        self.gridLayout_3.addWidget(self.pushButton_j9, 8, 0, 1, 1)
        self.pushButton_j4 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j4.setObjectName("pushButton_j4")
        self.gridLayout_3.addWidget(self.pushButton_j4, 3, 0, 1, 1)
        self.pushButton_j6 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j6.setObjectName("pushButton_j6")
        self.gridLayout_3.addWidget(self.pushButton_j6, 5, 0, 1, 1)
        self.pushButton_k2 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k2.setObjectName("pushButton_k2")
        self.gridLayout_3.addWidget(self.pushButton_k2, 1, 1, 1, 1)
        self.pushButton_j7 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j7.setObjectName("pushButton_j7")
        self.gridLayout_3.addWidget(self.pushButton_j7, 6, 0, 1, 1)
        self.pushButton_j5 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j5.setObjectName("pushButton_j5")
        self.gridLayout_3.addWidget(self.pushButton_j5, 4, 0, 1, 1)
        self.pushButton_j3 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j3.setObjectName("pushButton_j3")
        self.gridLayout_3.addWidget(self.pushButton_j3, 2, 0, 1, 1)
        self.pushButton_j8 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j8.setObjectName("pushButton_j8")
        self.gridLayout_3.addWidget(self.pushButton_j8, 7, 0, 1, 1)
        self.pushButton_l2 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l2.setObjectName("pushButton_l2")
        self.gridLayout_3.addWidget(self.pushButton_l2, 1, 2, 1, 1)
        self.pushButton_k1 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k1.setObjectName("pushButton_k1")
        self.gridLayout_3.addWidget(self.pushButton_k1, 0, 1, 1, 1)
        self.pushButton_l1 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l1.setObjectName("pushButton_l1")
        self.gridLayout_3.addWidget(self.pushButton_l1, 0, 2, 1, 1)
        self.pushButton_j10 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j10.setObjectName("pushButton_j10")
        self.gridLayout_3.addWidget(self.pushButton_j10, 9, 0, 1, 1)
        self.pushButton_j11 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_j11.setObjectName("pushButton_j11")
        self.gridLayout_3.addWidget(self.pushButton_j11, 10, 0, 1, 1)
        self.pushButton_k3 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k3.setObjectName("pushButton_k3")
        self.gridLayout_3.addWidget(self.pushButton_k3, 2, 1, 1, 1)
        self.pushButton_l3 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l3.setObjectName("pushButton_l3")
        self.gridLayout_3.addWidget(self.pushButton_l3, 2, 2, 1, 1)
        self.pushButton_k4 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k4.setObjectName("pushButton_k4")
        self.gridLayout_3.addWidget(self.pushButton_k4, 3, 1, 1, 1)
        self.pushButton_l4 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l4.setObjectName("pushButton_l4")
        self.gridLayout_3.addWidget(self.pushButton_l4, 3, 2, 1, 1)
        self.pushButton_k5 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k5.setObjectName("pushButton_k5")
        self.gridLayout_3.addWidget(self.pushButton_k5, 4, 1, 1, 1)
        self.pushButton_l5 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l5.setObjectName("pushButton_l5")
        self.gridLayout_3.addWidget(self.pushButton_l5, 4, 2, 1, 1)
        self.pushButton_k6 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k6.setObjectName("pushButton_k6")
        self.gridLayout_3.addWidget(self.pushButton_k6, 5, 1, 1, 1)
        self.pushButton_l6 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l6.setObjectName("pushButton_l6")
        self.gridLayout_3.addWidget(self.pushButton_l6, 5, 2, 1, 1)
        self.pushButton_k7 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k7.setObjectName("pushButton_k7")
        self.gridLayout_3.addWidget(self.pushButton_k7, 6, 1, 1, 1)
        self.pushButton_l7 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l7.setObjectName("pushButton_l7")
        self.gridLayout_3.addWidget(self.pushButton_l7, 6, 2, 1, 1)
        self.pushButton_k8 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k8.setObjectName("pushButton_k8")
        self.gridLayout_3.addWidget(self.pushButton_k8, 7, 1, 1, 1)
        self.pushButton_l8 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l8.setObjectName("pushButton_l8")
        self.gridLayout_3.addWidget(self.pushButton_l8, 7, 2, 1, 1)
        self.pushButton_k9 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k9.setObjectName("pushButton_k9")
        self.gridLayout_3.addWidget(self.pushButton_k9, 8, 1, 1, 1)
        self.pushButton_l9 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l9.setObjectName("pushButton_l9")
        self.gridLayout_3.addWidget(self.pushButton_l9, 8, 2, 1, 1)
        self.pushButton_k10 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k10.setObjectName("pushButton_k10")
        self.gridLayout_3.addWidget(self.pushButton_k10, 9, 1, 1, 1)
        self.pushButton_l10 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l10.setObjectName("pushButton_l10")
        self.gridLayout_3.addWidget(self.pushButton_l10, 9, 2, 1, 1)
        self.pushButton_k11 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_k11.setObjectName("pushButton_k11")
        self.gridLayout_3.addWidget(self.pushButton_k11, 10, 1, 1, 1)
        self.pushButton_l11 = QtWidgets.QPushButton(self.frame_seat_r)
        self.pushButton_l11.setObjectName("pushButton_l11")
        self.gridLayout_3.addWidget(self.pushButton_l11, 10, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.table_bill = QtWidgets.QTableWidget(self.page_4)
        self.table_bill.setGeometry(QtCore.QRect(20, 30, 851, 741))
        self.table_bill.setRowCount(100)
        self.table_bill.setColumnCount(5)
        self.table_bill.setObjectName("table_bill")
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_flight.setText(_translate("Form", "航班信息"))
        self.button_passenger.setText(_translate("Form", "乘客信息"))
        self.button_seat.setText(_translate("Form", "座位情况"))
        self.button_bill.setText(_translate("Form", "付款信息"))
        self.pushButton_flight_add.setText(_translate("Form", "增加"))
        self.pushButton_flight_del.setText(_translate("Form", "删除"))
        self.pushButton_flight_mod.setText(_translate("Form", "修改"))
        self.pushButton_flight_ser.setText(_translate("Form", "查询"))
        self.pushButton_passenger_add.setText(_translate("Form", "增加"))
        self.pushButton_passenger_del.setText(_translate("Form", "删除"))
        self.pushButton_passenger_mod.setText(_translate("Form", "修改"))
        self.pushButton_passenger_ser.setText(_translate("Form", "查询"))
        self.pushButton_b3.setText(_translate("Form", "0"))
        self.pushButton_a3.setText(_translate("Form", "0"))
        self.pushButton_a6.setText(_translate("Form", "0"))
        self.pushButton_b6.setText(_translate("Form", "0"))
        self.pushButton_b1.setText(_translate("Form", "0"))
        self.pushButton_c5.setText(_translate("Form", "0"))
        self.pushButton_b7.setText(_translate("Form", "0"))
        self.pushButton_a1.setText(_translate("Form", "0"))
        self.pushButton_c6.setText(_translate("Form", "0"))
        self.pushButton_b4.setText(_translate("Form", "0"))
        self.pushButton_a7.setText(_translate("Form", "0"))
        self.pushButton_a2.setText(_translate("Form", "0"))
        self.pushButton_a4.setText(_translate("Form", "0"))
        self.pushButton_b5.setText(_translate("Form", "0"))
        self.pushButton_a5.setText(_translate("Form", "0"))
        self.pushButton_b2.setText(_translate("Form", "0"))
        self.pushButton_a10.setText(_translate("Form", "0"))
        self.pushButton_a9.setText(_translate("Form", "0"))
        self.pushButton_b11.setText(_translate("Form", "0"))
        self.pushButton_a11.setText(_translate("Form", "0"))
        self.pushButton_b10.setText(_translate("Form", "0"))
        self.pushButton_b8.setText(_translate("Form", "0"))
        self.pushButton_b9.setText(_translate("Form", "0"))
        self.pushButton_c2.setText(_translate("Form", "0"))
        self.pushButton_a8.setText(_translate("Form", "0"))
        self.pushButton_c7.setText(_translate("Form", "0"))
        self.pushButton_c8.setText(_translate("Form", "0"))
        self.pushButton_c9.setText(_translate("Form", "0"))
        self.pushButton_c4.setText(_translate("Form", "0"))
        self.pushButton_c10.setText(_translate("Form", "0"))
        self.pushButton_c3.setText(_translate("Form", "0"))
        self.pushButton_c11.setText(_translate("Form", "0"))
        self.pushButton_c1.setText(_translate("Form", "0"))
        self.pushButton_f9.setText(_translate("Form", "0"))
        self.pushButton_g9.setText(_translate("Form", "0"))
        self.pushButton_f10.setText(_translate("Form", "0"))
        self.pushButton_h9.setText(_translate("Form", "0"))
        self.pushButton_h10.setText(_translate("Form", "0"))
        self.pushButton_e10.setText(_translate("Form", "0"))
        self.pushButton_g10.setText(_translate("Form", "0"))
        self.pushButton_e7.setText(_translate("Form", "0"))
        self.pushButton_f2.setText(_translate("Form", "0"))
        self.pushButton_h2.setText(_translate("Form", "0"))
        self.pushButton_e9.setText(_translate("Form", "0"))
        self.pushButton_g3.setText(_translate("Form", "0"))
        self.pushButton_g8.setText(_translate("Form", "0"))
        self.pushButton_f3.setText(_translate("Form", "0"))
        self.pushButton_e4.setText(_translate("Form", "0"))
        self.pushButton_g1.setText(_translate("Form", "0"))
        self.pushButton_h1.setText(_translate("Form", "0"))
        self.pushButton_f8.setText(_translate("Form", "0"))
        self.pushButton_e6.setText(_translate("Form", "0"))
        self.pushButton_h3.setText(_translate("Form", "0"))
        self.pushButton_h4.setText(_translate("Form", "0"))
        self.pushButton_f4.setText(_translate("Form", "0"))
        self.pushButton_h5.setText(_translate("Form", "0"))
        self.pushButton_g4.setText(_translate("Form", "0"))
        self.pushButton_e5.setText(_translate("Form", "0"))
        self.pushButton_g5.setText(_translate("Form", "0"))
        self.pushButton_f5.setText(_translate("Form", "0"))
        self.pushButton_f7.setText(_translate("Form", "0"))
        self.pushButton_g6.setText(_translate("Form", "0"))
        self.pushButton_f6.setText(_translate("Form", "0"))
        self.pushButton_h6.setText(_translate("Form", "0"))
        self.pushButton_g2.setText(_translate("Form", "0"))
        self.pushButton_g7.setText(_translate("Form", "0"))
        self.pushButton_e2.setText(_translate("Form", "0"))
        self.pushButton_f1.setText(_translate("Form", "0"))
        self.pushButton_e1.setText(_translate("Form", "0"))
        self.pushButton_h7.setText(_translate("Form", "0"))
        self.pushButton_e3.setText(_translate("Form", "0"))
        self.pushButton_h8.setText(_translate("Form", "0"))
        self.pushButton_e8.setText(_translate("Form", "0"))
        self.pushButton_e11.setText(_translate("Form", "0"))
        self.pushButton_f11.setText(_translate("Form", "0"))
        self.pushButton_g11.setText(_translate("Form", "0"))
        self.pushButton_h11.setText(_translate("Form", "0"))
        self.pushButton_j1.setText(_translate("Form", "0"))
        self.pushButton_j2.setText(_translate("Form", "0"))
        self.pushButton_j9.setText(_translate("Form", "0"))
        self.pushButton_j4.setText(_translate("Form", "0"))
        self.pushButton_j6.setText(_translate("Form", "0"))
        self.pushButton_k2.setText(_translate("Form", "0"))
        self.pushButton_j7.setText(_translate("Form", "0"))
        self.pushButton_j5.setText(_translate("Form", "0"))
        self.pushButton_j3.setText(_translate("Form", "0"))
        self.pushButton_j8.setText(_translate("Form", "0"))
        self.pushButton_l2.setText(_translate("Form", "0"))
        self.pushButton_k1.setText(_translate("Form", "0"))
        self.pushButton_l1.setText(_translate("Form", "0"))
        self.pushButton_j10.setText(_translate("Form", "0"))
        self.pushButton_j11.setText(_translate("Form", "0"))
        self.pushButton_k3.setText(_translate("Form", "0"))
        self.pushButton_l3.setText(_translate("Form", "0"))
        self.pushButton_k4.setText(_translate("Form", "0"))
        self.pushButton_l4.setText(_translate("Form", "0"))
        self.pushButton_k5.setText(_translate("Form", "0"))
        self.pushButton_l5.setText(_translate("Form", "0"))
        self.pushButton_k6.setText(_translate("Form", "0"))
        self.pushButton_l6.setText(_translate("Form", "0"))
        self.pushButton_k7.setText(_translate("Form", "0"))
        self.pushButton_l7.setText(_translate("Form", "0"))
        self.pushButton_k8.setText(_translate("Form", "0"))
        self.pushButton_l8.setText(_translate("Form", "0"))
        self.pushButton_k9.setText(_translate("Form", "0"))
        self.pushButton_l9.setText(_translate("Form", "0"))
        self.pushButton_k10.setText(_translate("Form", "0"))
        self.pushButton_l10.setText(_translate("Form", "0"))
        self.pushButton_k11.setText(_translate("Form", "0"))
        self.pushButton_l11.setText(_translate("Form", "0"))

